[browser]
gatherUsageStats = false

[server]
headless = true
maxUploadSize = 2024
maxMessageSize = 2024

[client]
showErrorDetails = true

[ui]
hideTopBar = true
hideRunningIndicator = false

[theme]
primaryColor = "#2563EB"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8FAFC"
textColor = "#0F172A"
